### ISSUE TITLE
Bug: duplicate selectors created in the stylesheet

### ISSUE THREAD

**Issue by hackdanismo** [hackdanismo/atomicss#12]
When adding the `mt-4` class to the HTML document and running the build, duplicate `mt-4` class selectors are being added to the original stylesheet and then this is also being added to the non-minified and minified stylesheets used in the HTML page.

Current stylesheet - `atomicss/styles/atomicss.css`:

```css
/* Dynamic Utilities */

/* Dynamic Utilities */
.mb-4 {
	margin-bottom: 4rem;
}

/* Dynamic Utilities */
.mt-4 {
	margin-top: 4rem;
}

/* Dynamic Utilities */
.mt-4 {
	margin-top: 4rem;
}
```

Run the build:

```shell
$ npm run build
```

Output generated stylesheet - `styles/atomicss.css`:

```css
/* Dynamic Utilities */

/* Dynamic Utilities */
.mb-4 {
	margin-bottom: 4rem;
}

/* Dynamic Utilities */
.mt-4 {
	margin-top: 4rem;
}

/* Dynamic Utilities */
.mt-4 {
	margin-top: 4rem;
}

/* Dynamic Utilities */
.mt-4 {
	margin-top: 4rem;
}
```
